name: Publish
on:
  push:
    branch:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Prepare NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install & Build
        run: |
          npm ci
          npm run deploy
      
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
